spring.application.name=foodiesapi

#mongodb configuration
spring.data.mongodb.uri=mongodb+srv://omp503745_db_user:Ompatil1234@cluster0.eydiay4.mongodb.net/foodies?retryWrites=true&w=majority&appName=Cluster0

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=eu-north-1
aws.s3.bucketname=foodies-foodssssss

jwt.secret.key=${JWT_SECRET}

#razorpay configuration
razorpay-key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}